<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>stalker2cfg</string>
    <key>fileTypes</key>
    <array>
      <string>cfg</string>
    </array>
    <key>firstLineMatch</key>
    <string>.*\bstruct\.begin.*</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>keyword.control.s2cfg</string>
        <key>match</key>
        <string>\b(struct\.begin|struct\.end)\b</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.bracket.square.s2cfg</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.bracket.square.s2cfg</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.float.s2cfg</string>
        <key>match</key>
        <string>(?&lt;![\w\d.])\d+\.(\d*)?([f])?</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.integer.s2cfg</string>
        <key>match</key>
        <string>(?&lt;![\w\d.])\d+(?![\.%])\b</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.numeric.percentage.s2cfg</string>
        <key>match</key>
        <string>(?&lt;![\w\d.])\d+%</string>
      </dict>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.s2cfg</string>
        <key>match</key>
        <string>(//.*$)</string>
      </dict>
      <dict>
        <key>name</key>
        <string>constant.language.s2cfg</string>
        <key>match</key>
        <string>\b(true|false)\b</string>
      </dict>
      <dict>
        <key>match</key>
        <string>([A-Za-z_\d]+)\s*(?=:)(?!::)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.s2cfg</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>([A-Za-z_\d]+)\s*(?==)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.property-name.s2cfg</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>string.unquoted.s2cfg</string>
        <key>match</key>
        <string>(?&lt;==|,)\s*(?=\b|\/|\.)(?!true|false)([A-Za-z\/\.][A-Za-z\d:_\/\.']+)</string>
      </dict>
    </array>
    <key>repository</key>
    <dict/>
    <key>scopeName</key>
    <string>source.stalker2cfg</string>
  </dict>
</plist>